/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_mycalculator;

import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class GUI_MyCalculator extends javax.swing.JFrame {

    float num1, num2, ang1, jum, result;
    int i;

    /**
     * Creates new form Asist_16November
     */
    public GUI_MyCalculator() {
        setIcon();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        tujuh = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        satu = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        nolnol = new javax.swing.JButton();
        del = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nol = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 200));

        jPanel1.setBackground(new java.awt.Color(164, 238, 210));
        jPanel1.setLayout(null);

        text.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel1.add(text);
        text.setBounds(20, 60, 450, 58);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(30, 140, 78, 26);

        tujuh.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tujuh.setText("7");
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        jPanel1.add(tujuh);
        tujuh.setBounds(30, 210, 70, 70);

        lima.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lima.setText("5");
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        jPanel1.add(lima);
        lima.setBounds(120, 300, 70, 70);

        empat.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        empat.setText("4");
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        jPanel1.add(empat);
        empat.setBounds(30, 300, 70, 70);

        sembilan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        sembilan.setText("9");
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });
        jPanel1.add(sembilan);
        sembilan.setBounds(210, 210, 70, 70);

        enam.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        enam.setText("6");
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        jPanel1.add(enam);
        enam.setBounds(210, 300, 70, 70);

        delapan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        delapan.setText("8");
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        jPanel1.add(delapan);
        delapan.setBounds(120, 210, 70, 70);

        tiga.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tiga.setText("3");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        jPanel1.add(tiga);
        tiga.setBounds(210, 390, 70, 70);

        dua.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        dua.setText("2");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        jPanel1.add(dua);
        dua.setBounds(120, 390, 70, 70);

        satu.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        satu.setText("1");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        jPanel1.add(satu);
        satu.setBounds(30, 390, 70, 70);

        kali.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        kali.setText("×");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        jPanel1.add(kali);
        kali.setBounds(300, 390, 70, 70);

        bagi.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        bagi.setText("÷");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        jPanel1.add(bagi);
        bagi.setBounds(300, 480, 70, 70);

        kurang.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        jPanel1.add(kurang);
        kurang.setBounds(300, 300, 70, 70);

        tambah.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah);
        tambah.setBounds(300, 210, 70, 70);

        clear.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(390, 300, 70, 70);

        samadengan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        jPanel1.add(samadengan);
        samadengan.setBounds(390, 390, 70, 70);

        nolnol.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        nolnol.setText("00");
        nolnol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolnolActionPerformed(evt);
            }
        });
        jPanel1.add(nolnol);
        nolnol.setBounds(30, 480, 70, 70);

        del.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        del.setText("del");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel1.add(del);
        del.setBounds(390, 210, 70, 70);

        koma.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        koma.setText(".");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });
        jPanel1.add(koma);
        koma.setBounds(210, 480, 70, 70);

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        jLabel1.setText("   Calculator");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(82, 16, 396, 43);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/abu abu.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, -10, 400, 740);

        nol.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        nol.setText("0");
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        jPanel1.add(nol);
        nol.setBounds(120, 480, 70, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/hsjdhaoow.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 10, 460, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        if ("0".equals(text.getText())) {
            text.setText("");
        } else if (text.getText() == null ? String.valueOf(result) == null : text.getText().equals(String.valueOf(result))) {
            text.setText("");
        }
        text.setText(text.getText() + "1");

        // TODO add your handling code here:
    }//GEN-LAST:event_satuActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        if ("0".equals(text.getText())) {
            text.setText("");
        } else if (text.getText() == null ? String.valueOf(result) == null : text.getText().equals(String.valueOf(result))) {
            text.setText("");
        }
        text.setText(text.getText() + "2");  // TODO add your handling code here:
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        if ("0".equals(text.getText())) {
            text.setText("");
        } else if (text.getText() == null ? String.valueOf(result) == null : text.getText().equals(String.valueOf(result))) {
            text.setText("");
        }
        text.setText(text.getText() + "3");  // TODO add your handling code here:
    }//GEN-LAST:event_tigaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        if ("0".equals(text.getText())) {
            text.setText("");
        } else if (text.getText() == null ? String.valueOf(result) == null : text.getText().equals(String.valueOf(result))) {
            text.setText("");
        }
        text.setText(text.getText() + "4");  // TODO add your handling code here:
    }//GEN-LAST:event_empatActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        if ("0".equals(text.getText())) {
            text.setText("");
        } else if (text.getText() == null ? String.valueOf(result) == null : text.getText().equals(String.valueOf(result))) {
            text.setText("");
        }
        text.setText(text.getText() + "5");  // TODO add your handling code here:
    }//GEN-LAST:event_limaActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        if ("0".equals(text.getText())) {
            text.setText("");
        } else if (text.getText() == null ? String.valueOf(result) == null : text.getText().equals(String.valueOf(result))) {
            text.setText("");
        }
        text.setText(text.getText() + "6");  // TODO add your handling code here:
    }//GEN-LAST:event_enamActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        if ("0".equals(text.getText())) {
            text.setText("");
        } else if (text.getText() == null ? String.valueOf(result) == null : text.getText().equals(String.valueOf(result))) {
            text.setText("");
        }
        text.setText(text.getText() + "7");  // TODO add your handling code here:
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        if ("0".equals(text.getText())) {
            text.setText("");
        } else if (text.getText() == null ? String.valueOf(result) == null : text.getText().equals(String.valueOf(result))) {
            text.setText("");
        }
        text.setText(text.getText() + "8");   // TODO add your handling code here:
    }//GEN-LAST:event_delapanActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        if ("0".equals(text.getText())) {
            text.setText("");
        } else if (text.getText() == null ? String.valueOf(result) == null : text.getText().equals(String.valueOf(result))) {
            text.setText("");
        }
        text.setText(text.getText() + "9");
        // TODO add your handling code here:
    }//GEN-LAST:event_sembilanActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
    String ops = String.valueOf(text.getText());
ops = ops.substring(0, ops.length()-1);
text.setText(ops);
    }//GEN-LAST:event_delActionPerformed

    private void nolnolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolnolActionPerformed
        if ("".equals(text.getText())) {
            text.setText("0");
        } else if ("0".equals(text.getText())) {
            text.setText("0");
        } else if (text.getText() == null ? String.valueOf(result) == null : text.getText().equals(String.valueOf(result))) {
            text.setText("0");
        } else if (!"".equals(text.getText())) {
            text.setText(text.getText() + "00");
        }

    }//GEN-LAST:event_nolnolActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
        if (!"".equals(text.getText())) {
           text.setText(text.getText() + ".");
        }
    }//GEN-LAST:event_komaActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        if ("-".equals(text.getText())) {
            text.setText("");
            num1 = ang1;
        } else if (!"".equals(text.getText())) {
            num1 = Float.parseFloat(text.getText());
            text.setText("");
            ang1 = num1;
        } else if ("".equals(text.getText())) {
            num1 = ang1;
        }

        i = 1;

        // TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed

        if ("".equals(text.getText())) {
            text.setText("-");
            num1 = ang1;
        } else if ("-".equals(text.getText())) {
            text.setText("-");
            num1 = ang1;
        } else if (!"".equals(text.getText())) {
            num1 = Float.parseFloat(text.getText());
            text.setText("");
            ang1 = num1;
        }
        if (num1 != result || num2 < 0) {
            switch (i) {
                case 1:
                    i = 1;
                    break;
                case 2:
                    i = 2;
                    break;
                case 4:
                    i = 4;
                    break;
                default:
                    i = 3;  // TODO add your handling code here:
                    break;
            }
        } else if (num1 == result&&num2>=0) {
            i = 3;
        }
    }//GEN-LAST:event_kurangActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed

        if (text.getText() == null ? String.valueOf(jum) != null : !text.getText().equals(String.valueOf(jum))) {
            if (i == 1) {
                num2 = Float.parseFloat(text.getText());
                text.setText(Float.toString(num1 + num2));
                result = num1 + num2;
            } else if (i == 2) {
                num2 = Float.parseFloat(text.getText());
                text.setText(Float.toString(num1 * num2));
                result = num1 * num2;
            } else if (i == 3) {
                num2 = Float.parseFloat(text.getText());
                text.setText(Float.toString(num1 - num2));
                result = num1 - num2;
            } else if (i == 4) {
                num2 = Float.parseFloat(text.getText());
                text.setText(Float.toString(num1 / num2));
                result = num1 / num2;
            }
            jum = result;
        } else if (text.getText() == null ? String.valueOf(jum) == null : text.getText().equals(String.valueOf(jum))) {
            text.setText(Float.toString(result));
        }

//        else if(result!=0)
//            text.setText(Float.toString(result));
//        ang2 = Float.parseFloat(text.getText());
//      text.setText(Float.toString(ang1*ang2));
//        text.setText(""+num1);
// TODO add your handling code here:
    }//GEN-LAST:event_samadenganActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        if ("-".equals(text.getText())) {
            text.setText("");
            num1 = ang1;
        } else if (!"".equals(text.getText())) {
            num1 = Float.parseFloat(text.getText());
            text.setText("");
            ang1 = num1;
        } else if ("".equals(text.getText())) {
            num1 = ang1;
        }
        i = 2;// TODO add your handling code here:
    }//GEN-LAST:event_kaliActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        text.setText("");
        num1 = 0;
        num2 = 0;
        ang1 = 0;
        result = 0;
        jum = 0;

    }//GEN-LAST:event_clearActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        if ("-".equals(text.getText())) {
            text.setText("");
            num1 = ang1;
        } else if (!"".equals(text.getText())) {
            num1 = Float.parseFloat(text.getText());
            text.setText("");
            ang1 = num1;
        } else if ("".equals(text.getText())) {
            num1 = ang1;
        }
        i = 4;   // TODO add your handling code here:
    }//GEN-LAST:event_bagiActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        if ("".equals(text.getText())) {
            text.setText("0");
        } else if ("0".equals(text.getText())) {
            text.setText("0");
        } else if (text.getText() == null ? String.valueOf(result) == null : text.getText().equals(String.valueOf(result))) {
            text.setText("0");
        } else if (!"".equals(text.getText())) {
            text.setText(text.getText() + "0");
        }


    }//GEN-LAST:event_nolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MyCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagi;
    private javax.swing.JButton clear;
    private javax.swing.JButton del;
    private javax.swing.JButton delapan;
    private javax.swing.JButton dua;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton koma;
    private javax.swing.JButton kurang;
    private javax.swing.JButton lima;
    private javax.swing.JButton nol;
    private javax.swing.JButton nolnol;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField text;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tujuh;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gambar kalkulator.jpg")));
    }
}
